# Generated by Django 5.0.3 on 2024-04-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lignes',
            fields=[
                ('ligneId', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ligne', models.CharField(max_length=200)),
                ('start_ligne', models.CharField(max_length=200)),
                ('end_ligne', models.CharField(max_length=200)),
                ('depart_ligne', models.CharField(max_length=200)),
                ('destination_ligne', models.CharField(max_length=200)),
            ],
        ),
    ]
