# Generated by Django 5.0.3 on 2024-04-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignes',
            name='plan_ligne',
            field=models.FileField(blank=True, null=True, upload_to='plan_lignes/'),
        ),
    ]
